# Uncomment this line to define a global platform for your project
platform :ios, '15.5'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  pod 'FaceAISDK_Core', :git => 'https://github.com/FaceAISDK/FaceAISDK_Core.git', :tag => '2026.07.01'
  pod 'TensorFlowLiteSwift'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  update_xcconfig = lambda do |xcconfig|
    settings = xcconfig.respond_to?(:build_settings) ? xcconfig.build_settings : xcconfig.attributes
    settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
    settings['CLANG_ENABLE_MODULES'] = 'YES'
    settings['OTHER_SWIFT_FLAGS'] ||= '$(inherited)'
    settings['OTHER_SWIFT_FLAGS'] = settings['OTHER_SWIFT_FLAGS'].gsub('-enable-library-evolution', '')
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['SWIFT_SERIALIZE_DEBUGGING_OPTIONS'] = 'YES'
    end
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end

  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |config_name, config|
      update_xcconfig.call(config)
      config.save_as(target.xcconfig_path(config_name))
    end
  end

  installer.pod_targets.each do |target|
    next unless target.respond_to?(:xcconfigs)

    target.xcconfigs.each do |config_name, config|
      update_xcconfig.call(config)
      config.save_as(target.xcconfig_path(config_name))
    end
  end
end

